//
// Created by hexi on 2020/3/4.
//

#ifndef ROCKETMQ_PROXY_CONST_H
#define ROCKETMQ_PROXY_CONST_H

#define ROCKETMQ_PROXY_CONSUMER_REQUEST_TYPE_CONSUME 1
#define ROCKETMQ_PROXY_CONSUMER_REQUEST_TYPE_ACK 2

#define ROCKETMQ_PROXY_MSG_STATUS_SENT -1

#define ROCKETMQ_PROXY_MSG_STATUS_ACK_SUCCESS CONSUME_SUCCESS
#define ROCKETMQ_PROXY_MSG_STATUS_ACK_CONSUME_LATER RECONSUME_LATER

#endif //ROCKETMQ_PROXY_CONST_H
