//
// Created by hexi on 2020/3/4.
//

#ifndef ROCKETMQ_PROXY_CONST_H
#define ROCKETMQ_PROXY_CONST_H

#define ROCKETMQ_PROXY_CONSUMER_REQUEST_TYPE_CONSUME 1
#define ROCKETMQ_PROXY_CONSUMER_REQUEST_TYPE_ACK 2

#define ROCKETMQ_PROXY_MSG_STATUS_SENT -1

#define ROCKETMQ_PROXY_MSG_STATUS_SYNC_INIT 1
#define ROCKETMQ_PROXY_MSG_STATUS_SYNC_SENT 2
#define ROCKETMQ_PROXY_MSG_STATUS_SYNC_ACK 3

#define ROCKETMQ_PROXY_LOG_TYPE_PRODUCER 1
#define ROCKETMQ_PROXY_LOG_TYPE_CONSUMER 2

#define ROCKETMQ_PROXY_LOG_STATUS_PRODUCER_SEND 1
#define ROCKETMQ_PROXY_LOG_STATUS_CONSUMER_SEND 2
#define ROCKETMQ_PROXY_LOG_STATUS_CONSUMER_ACK_SUCCESS 3
#define ROCKETMQ_PROXY_LOG_STATUS_CONSUMER_ACK_LATER 4


#endif //ROCKETMQ_PROXY_CONST_H
