version: '2'
services:
  namesrv:
    image: rocketmqinc/rocketmq:4.5.1
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  console:
    image: styletang/rocketmq-console-ng
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
  broker-1:
    image: rocketmqinc/rocketmq:4.5.1
    container_name: rmqbroker1
    ports:
      - 10911:10911
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./config/broker.conf:/home/rocketmq/rocketmq-4.5.1/conf/broker.conf
      - ./config/plain_acl.yml:/home/rocketmq/rocketmq-4.5.1/conf/plain_acl.yml
    command: sh mqbroker -n namesrv:9876 diskMaxUsedSpaceRatio=95 autoCreateTopicEnable=true -c ../conf/broker.conf
    depends_on:
      - namesrv
  rocketmq-proxy:
    image: rocketmq-proxy:2.0.1
    cap_add:
      - SYS_PTRACE
    ports:
      - 8090:8090
    volumes:
      - ./config/serverLocal.json:/data/config.json
    command:
      Server -f /data/config.json
