version: '2'
services:
  namesrv:
    image: rocketmqinc/rocketmq:4.5.1
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      extnetwork:
        ipv4_address: 172.10.0.100
  console:
    image: styletang/rocketmq-console-ng
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    networks:
      extnetwork:
        ipv4_address: 172.10.0.101
    depends_on:
      - broker
  broker:
    image: rocketmqinc/rocketmq:4.5.1
    container_name: rmqbroker
    ports:
      - 10911:10911
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./config/broker.conf:/home/rocketmq/rocketmq-4.5.1/conf/broker.conf
      - ./config/plain_acl.yml:/home/rocketmq/rocketmq-4.5.1/conf/plain_acl.yml
    command: sh mqbroker -n namesrv:9876 diskMaxUsedSpaceRatio=95 autoCreateTopicEnable=true -c ../conf/broker.conf
    depends_on:
      - namesrv
    networks:
      extnetwork:
        ipv4_address: 172.10.0.102
  rocketmq-proxy:
    image: rocketmq-client-cpp:2.0.1-batch-consume
    cap_add:
      - SYS_PTRACE
    ports:
      - 8090:8090
    volumes:
      - /Users/hexi/Develop/rocketmq-proxy:/data/rocketmq-proxy:cached
      - /Users/hexi/Develop/rocketmq/rocketmq-client-cpp:/rocketmq-client-cpp:cached
    command:
      bash -c "sleep 100000000000"
    networks:
      extnetwork:
        ipv4_address: 172.10.0.103
    depends_on:
      - broker
  elasticsearch:
    image: elasticsearch:6.3.2
    ports:
      - 9200:9200
    volumes:
      - ./data/es/data:/root/elasticsearch-6.3.2/data
      - ./config/elasticsearch.yml:/home/es/elasticsearch-6.3.2/config/elasticsearch.yml
    command:
      bash bin/elasticsearch
    networks:
      extnetwork:
        ipv4_address: 172.10.0.104
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.10.0.0/24
          gateway: 172.10.0.1