<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proxy.proto

namespace Proxy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proxy.ConsumeRequest</code>
 */
class ConsumeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string topic = 1;</code>
     */
    private $topic = '';
    /**
     * Generated from protobuf field <code>string consumer_group = 2;</code>
     */
    private $consumer_group = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic
     *     @type string $consumer_group
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string topic = 1;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string consumer_group = 2;</code>
     * @return string
     */
    public function getConsumerGroup()
    {
        return $this->consumer_group;
    }

    /**
     * Generated from protobuf field <code>string consumer_group = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConsumerGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->consumer_group = $var;

        return $this;
    }

}

