<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proxy.proto

namespace Proxy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proxy.ConsumeAckRequest</code>
 */
class ConsumeAckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string topic = 1;</code>
     */
    private $topic = '';
    /**
     * Generated from protobuf field <code>string msg_id = 2;</code>
     */
    private $msg_id = '';
    /**
     * Generated from protobuf field <code>string consumer_group = 3;</code>
     */
    private $consumer_group = '';
    /**
     * Generated from protobuf field <code>int32 status = 4;</code>
     */
    private $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic
     *     @type string $msg_id
     *     @type string $consumer_group
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string topic = 1;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg_id = 2;</code>
     * @return string
     */
    public function getMsgId()
    {
        return $this->msg_id;
    }

    /**
     * Generated from protobuf field <code>string msg_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string consumer_group = 3;</code>
     * @return string
     */
    public function getConsumerGroup()
    {
        return $this->consumer_group;
    }

    /**
     * Generated from protobuf field <code>string consumer_group = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setConsumerGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->consumer_group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

}

