<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proxy.proto

namespace Proxy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proxy.ProduceRequest</code>
 */
class ProduceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string topic = 1;</code>
     */
    private $topic = '';
    /**
     * Generated from protobuf field <code>string group = 2;</code>
     */
    private $group = '';
    /**
     * Generated from protobuf field <code>string tag = 3;</code>
     */
    private $tag = '';
    /**
     * Generated from protobuf field <code>string body = 4;</code>
     */
    private $body = '';
    /**
     * Generated from protobuf field <code>int32 delayLevel = 5;</code>
     */
    private $delayLevel = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic
     *     @type string $group
     *     @type string $tag
     *     @type string $body
     *     @type int $delayLevel
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string topic = 1;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group = 2;</code>
     * @return string
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * Generated from protobuf field <code>string group = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tag = 3;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 4;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 delayLevel = 5;</code>
     * @return int
     */
    public function getDelayLevel()
    {
        return $this->delayLevel;
    }

    /**
     * Generated from protobuf field <code>int32 delayLevel = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDelayLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->delayLevel = $var;

        return $this;
    }

}

